#!/usr/bin/env python3
#Dalen Ricks

import grp
import os
from pathlib import Path
import pwd
import sys
from stat import S_ISBLK, S_ISCHR, S_ISDIR, \
    S_ISDOOR, S_ISGID, S_ISLNK, S_ISREG, \
    S_ISSOCK, S_ISUID, S_ISVTX, S_IXGRP, S_IXOTH, S_IXUSR


def file_type_letter(mode: int) -> int:
    c = '?'

    if S_ISREG(mode):
        c = '-'
    elif S_ISDIR(mode):
        c = 'd'
    elif S_ISBLK(mode):
        c = 'b'
    elif S_ISCHR(mode):
        c = 'c'
    elif S_ISLNK(mode):
        c = 'l'
    elif S_ISSOCK(mode):
        c = 's'
    elif S_ISDOOR(mode):
        c = 'D'

    return c


def ls_perms(mode: int) -> str:
    rwx = ["---", "--x", "-w-", "-wx",
           "r--", "r-x", "rw-", "rwx"]

    bits = [0] * 10

    bits[0] = file_type_letter(mode)
    bits[1] = rwx[(mode >> 6) & 7]
    bits[4] = rwx[(mode >> 3) & 7]
    bits[7] = rwx[(mode & 7)]

    if mode & S_ISUID:
        bits[3] = 's' if (mode & S_IXUSR) else 'S'
    if mode & S_ISGID:
        bits[6] = 's' if (mode & S_IXGRP) else 'l'
    if mode & S_ISVTX:
        bits[9] = 't' if (mode & S_IXOTH) else'T'

    bits = [i for i in bits if i != 0]
    return ''.join(bits)


def get_filename_ext(filename: str) -> str:
    return Path(filename).suffix


if __name__ == "__main__":
    argc = len(sys.argv)
    
    if (argc == 4):
        operation = sys.argv[1]
        ext = sys.argv[2]
        directory = sys.argv[3]
    elif(argc == 5):
        operation = sys.argv[1]
        ext = sys.argv[2]
        directory = sys.argv[3]
        keyword = sys.argv[4]
    elif (argc != 4 or argc != 5):
        print("Format Error:./dalenricks_hw3.py <operation> <ext> <directory> [<search_keyword>]\n")
        exit() 
 
    if(operation == "details"):
        for filename in os.listdir(directory):
            file_ext = get_filename_ext(filename)
            if(file_ext == ext):
                
                print(f"File: {filename}")
                buf = os.stat(filename)

                mode = buf.st_mode
                size = buf.st_size

                perms = ls_perms(mode)
                print(f"Permissions: {perms}")

                pw = pwd.getpwuid(buf.st_uid)
                print(f"Owner: {pw.pw_name}")

                gr = grp.getgrgid(buf.st_gid)
                print(f"Group: {gr.gr_name}\n")
                
    if(operation == "search"):
        count = 0;
        for filename in os.listdir(directory):
            file_ext = get_filename_ext(filename)
            if(file_ext == ext):
                fd = open(filename, "r")
                txt = fd.read()

                if(keyword in txt):
                    count += 1
                    print(f"Keyword:'{keyword}' found in {filename}\n")

        if(count == 0):
            print(f"Keyword:'{keyword}' not found in {directory}\n")
        


        
