#!/usr/bin/env python3
#Dalen Ricks

import math

class isc_triangle:
    def __init__(self, base, height):
        self.base = base
        self.height = height
        self.calc_side()
        self.calc_perimeter()
        self.calc_area()
        self.calc_alpha()
        self.calc_beta()

    def set_base(self, new_base):
        self.base = new_base

    def set_height(self, new_height):
        self.height = new_height

    def calc_side(self):
        self.side = math.sqrt(((self.base/2) ** 2) + (self.height ** 2))

    def calc_perimeter(self):
        self.perimeter = 2 * self.side + self.base

    def calc_area(self):
        self.area = (self.base/2)*self.height

    def calc_alpha(self):
        self.alpha = math.degrees(math.atan(self.height/(self.base/2)))

    def calc_beta(self):
        self.beta = math.degrees(math.atan((self.base/2)/self.height) * 2)

    def print_all(self) -> None:
        print(f"------------------------------")
        print(f"base : {self.base}")
        print(f"height : {self.height}")
        print(f"side : {self.side}")
        print(f"perimeter: {self.perimeter}")
        print(f"area : {self.area}")
        print(f"alpha : {self.alpha}")
        print(f"beta : {self.beta}")
        print(f"------------------------------")

triangle = isc_triangle(4, 5)
triangle.print_all()
